### ISSUE TITLE
Setting a counter from an externally acquired value is awkward

### ISSUE THREAD

**Issue by tim-seoss** [tikv/rust-prometheus#363] opened 2020-11-05 12:43 UTC
**Is your feature request related to a problem? Please describe.**
I have a counter which I'd like to update using a value that I acquire from elsewhere (as an integer).  The API I'm using has semantics which are suitable for a Prometheus Counter https://prometheus.io/docs/concepts/metric_types/#counter - this doesn't map well to the prometheus::Counter methods

**Describe the solution you'd like**
Not sure if I'm missing some way to do this?  If not, then perhaps something like the following might be helpful?

```rust
impl<P: Atomic> GenericCounter<P> {
// ...

/// Increment the value of the counter to given value
///
/// # Panics
///
/// Panics in debug build if the given value is less than the current value of the counter.
#[inline]
pub fn inc_to(&self, v: P::T) {
    debug_assert!(v >= self.v.get());
    self.v.set(v);
}
```

**Describe alternatives you've considered**

I'm currently using this hacky workaround:
```rust
let u = get_external_counter_value();
mycounter.inc_by(u - mycounter.get());
```

**Comment by lucab** [comment] 2020-11-05 14:55
Thanks for the report. I think this is a duplicate of https://github.com/tikv/rust-prometheus/pull/303, and the discussion there has more clues regarding why setting counters to arbitrary absolute values is not part of the API.

**Comment by tim-seoss** [comment] 2020-11-08 10:56
Thanks for the answer.

My impression of that is: "you can't do that, so that we have an API similar to the Go api" (except that you can do it with the hacky workaround above), but you might be able to do it in the future, when #94 gets done?

**Comment by lucab** [comment] 2022-12-13 08:25
It isn't only a matter of sticking to the Go API: more importantly this tries to stay aligned with overall Prometheus ecosystem design.
There are more details about Prometheus Counters at https://www.robustperception.io/setting-a-prometheus-counter/ and https://www.robustperception.io/how-does-a-prometheus-counter-work/, which generally applies to all client-libraries.

**Closed by lucab** 2022-12-13 08:25 UTC
